### PR TITLE
update workflow guide from wiki, ht @bertsky, fix #285

### LINKED ISSUE #285: Include ocrd-segment-evaluate in workflow guide

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Review by bertsky — CHANGES_REQUESTED** [review]
I believe you are missing the changes to the top-level sidebar (where I fixed an href and added a section for OLR eval), and the new page https://github.com/OCR-D/ocrd-website/wiki/Workflow-Guide-OLR-evaluation

**Comment by kba** [comment]
> I believe you are missing the changes to the top-level sidebar (where I fixed an href and added a section for OLR eval)

How do you mean, where do you expect that fix on the website? The `_Sidebar.md` is only used as the navigation sidebar in https://github.com/OCR-D/ocrd-website/wiki. Or do you mean we should mirror that sidebar as a link list to our website?

> and the new page https://github.com/OCR-D/ocrd-website/wiki/Workflow-Guide-OLR-evaluation

Ah, sry, forgot to regenerate after adding, 98211f5a

**Comment by bertsky** [comment]
> How do you mean, where do you expect that fix on the website? The `_Sidebar.md` is only used as the navigation sidebar in https://github.com/OCR-D/ocrd-website/wiki. Or do you mean we should mirror that sidebar as a link list to our website?

Ah, understood. Right, the videos do not appear on the site itself. So never mind!

**Review by bertsky — APPROVED** [review]
LGTM

**Pull request merged**
