### PR TITLE
Update ToC display

### PR DESCRIPTION
**Pull request by paulpestov**
This PR changes the way the table of contents is displayed and toggled internally. Also adds a real toggle button and updates general styling.

### CODE REVIEW

**Comment by kba** [comment]
# Before

image
image



# After:

image
image

**Review by kba — APPROVED** [review]
LGTM, bzw. LBTM, looks better to me :+1:

**Comment by lena-hinrichsen** [comment]
> No, wait, I think there's a regression with the `de/en` Links. e.g. in the about page:
> 
> image
> 
> See the double `dede`, that should be just `de`. Something wrong with the template logic?

yes and no - we already have this bug at the moment in https://ocr-d.de/en/about so it's probably not related to @paulpestov's PR

**Comment by kba** [comment]
> yes and no - we already have this bug at the moment in https://ocr-d.de/en/about so it's probably not related to @paulpestov's PR

argh, investigating.

**Comment by kba** [comment]
> > yes and no - we already have this bug at the moment in https://ocr-d.de/en/about so it's probably not related to @paulpestov's PR
> 
> argh, investigating.

@lena-hinrichsen The problem is the file `site/de/architecture.md` which you added in 737764b7a9b2b38f70cd26198f72be59a09637d0. It's weird, the text is the `decisions.md` but the header is

```yaml
---                     
layout: page            
lang-ref: about         
lang: de                
toc: true               
title: Das OCR-D-Projekt
---                     
```

which has wrong `lang-ref` (leading to the doubled `dede` in about) and the title is wrong too. I guess just delete that file?

**Comment by lena-hinrichsen** [comment]
> @lena-hinrichsen The problem is the file `site/de/architecture.md` which you added in [737764b](https://github.com/OCR-D/ocrd-website/commit/737764b7a9b2b38f70cd26198f72be59a09637d0). It's weird, the text is the `decisions.md` but the header is
> 
> ```yaml
> ---                     
> layout: page            
> lang-ref: about         
> lang: de                
> toc: true               
> title: Das OCR-D-Projekt
> ---                     
> ```
> 
> which has wrong `lang-ref` (leading to the doubled `dede` in about) and the title is wrong too. I guess just delete that file?

yes, that works -thanks! (deoloying at the moment)

**Pull request merged**
