### PR TITLE
Improve English documentation (translation, spelling fixes)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
Note that I did not update the generated documentation which might be derived from the modified files.

**Review by kba — APPROVED** [review]
Thanks. The fixes to DITA CSS and Labelling schema need to be fixed at the source or will be overwritten on next generation.

**Comment by stweil** [comment]
https://github.com/dita-ot/docs/pull/538 addresses the typos in DITA CSS.

**Comment by kba** [comment]
https://github.com/OCR-D/gt-labelling/pull/6 fixes the typos in gt-labelling, with the `typos` from PyPI.

**Comment by stweil** [comment]
Upstream dita-ot/docs is now also fixed.

**Pull request merged**
